version: 2.1

jobs:
  order_complete_updater:
    working_directory: ~/order-complete-updater
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: order-complete-updater-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: order-complete-updater-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: docker image build api -t devopsgreenhouse/order-complete-updater:dev
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run: docker image push devopsgreenhouse/order-complete-updater:dev

  order_service:
    working_directory: ~/order-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: order-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: order-service-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: docker image build api -t devopsgreenhouse/order-service:dev
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run: docker image push devopsgreenhouse/order-service:dev

  payment_distribution:
    working_directory: ~/payment-distribution
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: payment-distribution-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: payment-distribution-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: docker image build api -t devopsgreenhouse/payment-distribution:dev
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run: docker image push devopsgreenhouse/payment-distribution:dev

  payment_service:
    working_directory: ~/payment-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: payment-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: payment-service-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: docker image build api -t devopsgreenhouse/payment-service:dev
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run: docker image push devopsgreenhouse/payment-service:dev

  restaurant_service:
    working_directory: ~/restaurant-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: restaurant-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: restaurant-service-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: docker image build api -t devopsgreenhouse/restaurant-service:dev
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run: docker image push devopsgreenhouse/restaurant-service:dev

workflows:
  version: 2
  build_test_and_deliver:
    jobs:
      - order_complete_updater
      - order_service
      - payment_distribution
      - payment_service
      - restaurant_service]
